# Generated by Django 5.0.2 on 2024-02-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('author', models.CharField(max_length=20)),
                ('book_name', models.CharField(max_length=50)),
                ('book_no', models.CharField(max_length=10, primary_key='book_no', serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('edition_year', models.IntegerField()),
                ('shelfno', models.CharField(max_length=20)),
            ],
        ),
    ]
